#!/bin/sh

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -z "$KDEDIRS" ]; then
   export KDEDIRS=/usr/share/torbrowser-default-browser/
else
   export KDEDIRS=/usr/share/torbrowser-default-browser/:$KDEDIRS
fi
