#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

if [ -f /usr/libexec/helper-scripts/pre.bsh ]; then
   source /usr/libexec/helper-scripts/pre.bsh
fi

set -e

update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/whichbrowser 112
update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /usr/bin/whichbrowser 112

#DEBHELPER#
